services:
  - type: web
    name: fashion-design-app
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html